name: juju-backup-all
base: core20
adopt-info: juju-backup-all
summary: Tool for backing up charms, local configs, and Juju controllers.
description: |
  Juju-backup-all allows operators to perform backups across all controllers
  and models. It provides autodiscovery, backing up all applications of supported
  charms. The tool also includes options to exclude charms, select which
  controllers to backup, and backup local configs.

  Supported charms: mysql-innodb-cluster, percona-cluster, etcd
  Supported config backups: Juju
grade: devel
confinement: classic

apps:
  juju-backup-all:
    command: bin/juju-backup-all
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH

parts:
  juju-backup-all:
    plugin: python
    requirements:
      - requirements.txt
    source: .
    source-type: git
    override-build: |
      snapcraftctl build
      echo "Version: $(python3 setup.py --version)"
      snapcraftctl set-version "$(python3 setup.py --version)"
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3.8-minimal
